services:
  mongo:
    image: mongo
    container_name: twhn_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - twhn_mongo_db:/data/db
    ports:
      - "27019:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis
    restart: always
    container_name: twhn_redis
    volumes:
      - twhn_redis_db:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  taigram:
    build: .
    container_name: taigram
    restart: always
    volumes:
      - ./config/settings.yaml:/code/config/settings.yaml
      - ./logs:/code/logs
    environment:
      - ENV_FOR_DYNACONF=dev
      - DB_URL="mongodb://twhn_user:twhn_password@twhn_mongo:27017"
      - REDIS_URL="redis://redis:6379/0"
    command: uv run app
    hostname:
      twhn.whtest
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  twhn_mongo_db:
  twhn_redis_db:

networks:
  default:
    name: taiga
    external: true
