dynaconf_merge: true
default:
  ADMIN_IDS:
    - 1234556
  ERRORS_CHAT_ID: -123456
  ERRORS_THREAD_ID:
  WEBHOOK_DOMAIN: "https://example.com"
  DEFAULT_LANGUAGE: "en"
  TIME_ZONE: "Europe/Moscow"
  TELEGRAM_BOT_TOKEN: "1234"
  DB_URL: "mongodb://twhn_user:twhn_password@mongo:27017"
  DB_NAME: "taigram"
